# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compile Dispatcher
        run: mvn -pl dispatcher compile
      - name: Run Dispatcher unit tests
        run: mvn -pl dispatcher test
      - name: Package Dispatcher
        run: mvn -pl dispatcher package -DskipTests
      - name: Build Dispatcher Docker image
        run: mvn -pl dispatcher docker:build
      - name: Compile Tsukuyomi
        run: mvn -pl statefun-tsukuyomi compile
      - name: Run Tsukuyomi unit tests
        run: mvn -pl statefun-tsukuyomi test
      - name: Run Tsukuyomi integration tests
        run: mvn -P integration -pl statefun-tsukuyomi test
